// GENERATED CODE - DO NOT MODIFY BY HAND
// Folder: lib/models/
// File:   video_model.g.dart
//
// This file is normally auto-generated by build_runner.
// It is provided here pre-generated so the project compiles without
// running build_runner first.

part of 'video_model.dart';

// **************************************************************************
// TypeAdapterGenerator
// **************************************************************************

class VideoModelAdapter extends TypeAdapter<VideoModel> {
  @override
  final int typeId = 0;

  @override
  VideoModel read(BinaryReader reader) {
    final numOfFields = reader.readByte();
    final fields = <int, dynamic>{
      for (int i = 0; i < numOfFields; i++) reader.readByte(): reader.read(),
    };
    return VideoModel(
      id: fields[0] as String,
      title: fields[1] as String,
      category: fields[2] as String,
      remoteUrl: fields[3] as String,
      localFilePath: fields[4] as String,
      platform: fields[5] as VideoPlatform,
      thumbnailUrl: fields[6] as String?,
      duration: fields[7] as double?,
      fileSizeBytes: fields[8] as int,
      lastAccessedMs: fields[9] as int?,
      cacheStatus: fields[10] as CacheStatus,
      originalUrl: fields[11] as String,
      width: fields[12] as int?,
      height: fields[13] as int?,
      createdAtMs: fields[14] as int?,
    );
  }

  @override
  void write(BinaryWriter writer, VideoModel obj) {
    writer
      ..writeByte(15)
      ..writeByte(0)
      ..write(obj.id)
      ..writeByte(1)
      ..write(obj.title)
      ..writeByte(2)
      ..write(obj.category)
      ..writeByte(3)
      ..write(obj.remoteUrl)
      ..writeByte(4)
      ..write(obj.localFilePath)
      ..writeByte(5)
      ..write(obj.platform)
      ..writeByte(6)
      ..write(obj.thumbnailUrl)
      ..writeByte(7)
      ..write(obj.duration)
      ..writeByte(8)
      ..write(obj.fileSizeBytes)
      ..writeByte(9)
      ..write(obj.lastAccessedMs)
      ..writeByte(10)
      ..write(obj.cacheStatus)
      ..writeByte(11)
      ..write(obj.originalUrl)
      ..writeByte(12)
      ..write(obj.width)
      ..writeByte(13)
      ..write(obj.height)
      ..writeByte(14)
      ..write(obj.createdAtMs);
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoModelAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class VideoPlatformAdapter extends TypeAdapter<VideoPlatform> {
  @override
  final int typeId = 1;

  @override
  VideoPlatform read(BinaryReader reader) {
    switch (reader.readByte()) {
      case 0:
        return VideoPlatform.youtube;
      case 1:
        return VideoPlatform.tiktok;
      default:
        return VideoPlatform.youtube;
    }
  }

  @override
  void write(BinaryWriter writer, VideoPlatform obj) {
    switch (obj) {
      case VideoPlatform.youtube:
        writer.writeByte(0);
        break;
      case VideoPlatform.tiktok:
        writer.writeByte(1);
        break;
    }
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VideoPlatformAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}

class CacheStatusAdapter extends TypeAdapter<CacheStatus> {
  @override
  final int typeId = 2;

  @override
  CacheStatus read(BinaryReader reader) {
    switch (reader.readByte()) {
      case 0:
        return CacheStatus.none;
      case 1:
        return CacheStatus.downloading;
      case 2:
        return CacheStatus.cached;
      case 3:
        return CacheStatus.expired;
      default:
        return CacheStatus.none;
    }
  }

  @override
  void write(BinaryWriter writer, CacheStatus obj) {
    switch (obj) {
      case CacheStatus.none:
        writer.writeByte(0);
        break;
      case CacheStatus.downloading:
        writer.writeByte(1);
        break;
      case CacheStatus.cached:
        writer.writeByte(2);
        break;
      case CacheStatus.expired:
        writer.writeByte(3);
        break;
    }
  }

  @override
  int get hashCode => typeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CacheStatusAdapter &&
          runtimeType == other.runtimeType &&
          typeId == other.typeId;
}
